name: examen2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  cloud_firestore: ^5.4.1
  firebase_core: ^3.4.1
  flutter:
    sdk: flutter
  go_router: ^14.2.7
  http: ^1.2.2
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
